import 'dotenv/config';

//console.log('TEST ENV:', process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID);


export default ({ config }) => ({
  ...config,
  extra: {
    EXPO_PUBLIC_APPWRITE_API_KEY: process.env.EXPO_PUBLIC_APPWRITE_API_KEY,
    EXPO_PUBLIC_APPWRITE_DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID,
    EXPO_PUBLIC_APPWRITE_USERS_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_USERS_COLLECTION_ID,
    EXPO_PUBLIC_APPWRITE_GROUPS_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_GROUPS_COLLECTION_ID,
  },
});
